name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Build client
        run: pnpm build
      - name: Check style
        run: pnpm eslint
      - name: Run tests
        run: pnpm --filter client test

      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          start: pnpm start
          command: pnpm --filter client test:e2e
      
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        run: |
          echo "Deploying to Vercel"
          curl ${{ secrets.VERCEL_API_KEY }}
      
      - name: Discord Webhook Notify (Build Failed)
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          description: 'Build failed! Please check the logs.'
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
  
      - name: Discord Webhook Notify (Deployment Success)
        if: ${{ success() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: sarisia/actions-status-discord@v1
        with:
          description: 'Deployment succesfull! 🚀'
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [deployment]
    runs-on: ubuntu-20.04
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
